version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-erp

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - laravel-erp

  webserver:
    platform: linux/amd64 # This is for macos M1
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./build/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-erp

networks:
  laravel-erp:
    driver: bridge
volumes:
  dbdata:
    driver: local
